DELETE http://localhost:8080/events/1/cancel-registration
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJYLUUiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiWC1VIjoxLCJleHAiOjE3MTE4NTg1MDN9.KAMv1TRoKkgnLkxskOcXdGtCVUPRCTI83SdMEkulUdQ