POST http://localhost:8080/events 
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJYLUUiOiJ0ZXN0MUBleGFtcGxlLmNvbSIsIlgtVSI6MSwiZXhwIjoxNzExMjY2MDgyfQ.beFr-N352WY5Murectc2NCA3czgX1bmOYbINZwejdSI

{
    "name": "test event",
    "description": "test event description",
    "location": "test event location",
    "datetime": "2025-01-01T15:00:00.000Z"
}