PUT http://localhost:8080/events/1 
Content-Type: application/json

{
    "name": "updated event",
    "description": "updated test event description",
    "location": "updated test event location",
    "datetime": "2025-01-01T15:00:00.000Z"
}